import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../GlobalRedux/provider";
import { ThemeProvider } from "@/components/global/ThemeProvider";
import { Navbar } from "@/components/shared/header/Navbar";
import Footer from "@/components/Footer";
import { Locale, defaultLocale } from "@/i18n.config";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import Loading from "./profile/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AutoHeaven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang ?? defaultLocale} suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="h-screen flex flex-col ">
              <Navbar lang={params.lang ?? defaultLocale} />

              {children}

              <Toaster />
              <Footer lang={params.lang ?? defaultLocale} />
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
